name: stale issues and PR s
on:
    schedule:
        - cron: "* 16 * * *"
        - cron: "37,38 16 * * *"        
jobs:
    stalejobs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v8
              with: 
                stale-issue-message: this is mark as stale mesg"
                days-before-stale: 5
                days-before-close: 10
