name: repos events
on: [push, pull_request, issues]
jobs:
    chekcout-test-action:
        runs-on: ubuntu-22.04
        steps:
            - run: |
               echo $GITHUB_SHA
               echo $GITHUB_REF 
            - uses: actions/checkout@v3