name: Workflow commands
on: [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: setting error mesg
              run: echo "::error::Missing something"