name: Workflow dir and shell commands
on: [push]

jobs:
    display-dir-shell_ubutnu:
        runs-on: ubuntu-22.04
        steps:
            - name: Display working dir and ls there
              run: |
                pwd
                ls -a
                uname -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
    display-dir-shell-windows:
        runs-on: windows-2022
        steps:
            - name: Display working dir and ls there
              run: |
                get-location
                dir
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE           