name: workflow depend on other workflow
on: 
    workflow_run:
        workflows: [repos events]
        types: [completed]
        branches:
            - main
            
jobs:
    echo-test:
        runs-on: ubuntu-22.04
        steps:
            - run: echo " i was triggered bcos 'repo events' is completed"