name: repos events
on: 
    push: 
        branches:
            - main
            - "feature/*"
            - "feature/**"
        # branches-ignore:
        #     - develop
        tags:
            - v1.*
            - "!v1.1.1"
        paths:
            - "**.js"   
            - "!app.js" 
    pull_request: 
        branches:
            - main
        paths:
            - "**.js"   
        types: [opened, assigned, edited, reopened, synchronize]
    issues:
        types: [opened]
jobs:
    chekcout-test-action:
        runs-on: ubuntu-22.04
        steps:
            - run: |
               echo $GITHUB_SHA
               echo $GITHUB_REF 
            - uses: actions/checkout@v3