name: repos events
on: 
    push: 
    pull_request: 
        types: [opened, assigned, edited, reopened, synchronize]
    issues:
        types: [reopened]
jobs:
    chekcout-test-action:
        runs-on: ubuntu-22.04
        steps:
            - run: |
               echo $GITHUB_SHA
               echo $GITHUB_REF 
            - uses: actions/checkout@v3